apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: togglemaster
data:
  PORT: "8005"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  AWS_REGION: "us-east-1"
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: togglemaster
type: Opaque
data:
  AWS_SQS_URL: "aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vMDA3OTA3MjYyMjg2L3RvZ2dsZW1hc3Rlci1xdWV1ZQ=="
  AWS_ACCESS_KEY_ID: "QVNJQVFEVjJQSDVIQVNYUkNPQjI="
  AWS_SECRET_ACCESS_KEY: "MzRxNU5jaFNDUkpKOC9ITUtZOEZLR3Y2b25BZUllWE5Sd2FJYjkrVg=="
  AWS_SESSION_TOKEN: "SVFvSmIzSnBaMmx1WDJWakVBUWFDWFZ6TFhkbGMzUXRNaUpITUVVQ0lRRC9yOWZlZGRpdVBZaDJJa291ZmRuN041MzE1VHl5aWZueHF1a2dOQytLY1FJZ0RqV3g5dVkxNXAzQXlvT2pkeXh1ODlFZzFRclNFRzRMSkZYTUZaaHlFOXNxdFFJSXpmLy8vLy8vLy8vL0FSQUFHZ3d3TURjNU1EY3lOakl5T0RZaURQdDF1bWdidFhoY2hVb2xIQ3FKQXNhZnYvYy9rMVVVUzl0Y1RySTlqTDVmQzl6NTJFTCtGOE53bFNQeUFDZmpuRy9zUDlxNHBFVFQ3THByTGZjRkgxTUlVdkpYQStkbG9rYzZnU0FnRXh3TXZKaHN0Q2FkTnNxMkcyM1FiSitKR3RTc1kwZHRwNG82NytDelVYdUd3K1JnSWNwYXhFWmE1aDJObDduc2pIdnRGZnpoZUtoWXM3emtON1gremJHeGRreWN2S0xUV2Q5dFoyVHp3Unp4Q3JuaWxTdjhoMU1HWTBqQkM2UUpiSW1UTGRpTHp4cDVyaXRpOVJoWm0vQ3R5ZmV2b21EY1Rlb0tWK2JWWDVKWUkvUXZ2TFVRNHJtQlVZWkU2emxzaGlvd0dNTnNvZ3F3eUJKNW5QR0x6UU5OekV0cW1QTzkyc2FyQ2liUzB2N1ZiVzZWc254L0s5cWt4ZFZFU2lEVlZLR2hzMTR3MUlIS0N4SXdtK0tselFZNm5RRjBtNXNNUDQ3aWlVbDVvOWd4QUgzNlcwbDJPNHVGaXRXcUpmS1BiNDR4eENMVE1pZFVJc3pBb05Qdy9oaE84TEZjengyU0tDSjZlcUZTV1kveXhseWd1NmdhSWR5Y01Dd2VQN1NnUWgya2tDZHdoNnhjeXowbzZwNWgvL053dVV5bkdROWlMTCtINzBuY2c5UDRGZUs1OXA5Q213cjh5NTRuWEx1NzY5YU0vVE1aNnVyRXhsTGlFTXFXU2R0VFVmY1FYcE1oS1QwcjRBK3I3SjBO"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: togglemaster
  labels:
    app: analytics-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: 007907262286.dkr.ecr.us-east-1.amazonaws.com/analytics-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          envFrom:
            - configMapRef:
                name: analytics-service-config
            - secretRef:
                name: analytics-service-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 15
            periodSeconds: 20
