apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: togglemaster
data:
  PORT: "8005"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  AWS_REGION: "us-east-1"
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: togglemaster
type: Opaque
data:
  AWS_SQS_URL: "aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vMDA3OTA3MjYyMjg2L3RvZ2dsZW1hc3Rlci1xdWV1ZQ=="
  AWS_ACCESS_KEY_ID: "QVNJQVFEVjJQSDVISVVOVTUyWVc="
  AWS_SECRET_ACCESS_KEY: "TEhoa01laWVCR2Q4UjY3bzVmUGIvM3ZJK1dBWlNiaitHMzJzMGtUTA=="
  AWS_SESSION_TOKEN: "SVFvSmIzSnBaMmx1WDJWakVQbi8vLy8vLy8vLy93RWFDWFZ6TFhkbGMzUXRNaUpITUVVQ0lGdHZEcjlKU2tFUXMveFJBa0hnYnRiajVWS0E2NitOMVJ1T1JpWmJPQzJXQWlFQXltU2VTQ0Z2Y1RyVit5TzNNQ0U5L3NKTjJRVzJYT1Vid1EzUk4wWkt5Sk1xdFFJSXd2Ly8vLy8vLy8vL0FSQUFHZ3d3TURjNU1EY3lOakl5T0RZaURPV3RPcS81c2w5dHdmVlVpeXFKQXNrNW00MmpOT0d1Zkw4dzdsNTVDNk9HN29MNGhoTEJrVm9vTjBjTWJJUDhEcjFRRnJTZEQ4dXZkOEFobzh1V3EwUWZVK08vdVVOZXNRZ1ptdnFLK01ZWjRwUDRuQ1B0Q2xSd1VWVlhDek5rU2dxbnRSSjNaSmp2NFhTU0xHSnp3VTcyVG9QMG9KeHUrSlRyV2FlU3ZwaTlPMTFuU01JL2tWZFJxUEJ3dUwzQzZPU0VUT1VPQ0x1bnM4cDJDNktET2ZUZktPaGpEWWlORUhhZnJVSFpiUEtwQTRrK0poTXFzOHVFREQ5QTBjY0JkWnBtUEZ5L3BZVmdzbDkwNnhnWlRJUGsxVU0rdXV4bDJXTTlhbE1HSVJmVU5KKzFweVh1NkxTUkw4T1JGZlpockxKUGYzdWpDYWpaS2VxS2FoSTBCQ1E0OU14TGJsTmRJcWNsVjlYbFdybmNwbWdTTGlOSHVmUXdyckdqelFZNm5RR1gyMlJ1TDNjUkh3Snl4Y0dBa3JET3A0K3haM1ZzMjdvSDN0blg2L3V6SXRGeUJVUW1GOFMyT0VzYWtIU1gzdGQzdzVCME15UTU2RThIL0Ivbkx2ZGRnSWpRd3pTSWNFYUJHeFBaM3d0ZExvRFZVOGU4VEdlRnk1SFYwNmd5RzNTdUVvRjZXNTFoUHFERWFHY1pCRUxwaWxjeDBpUFdNVHpMSk1mZ2RyYldha1Z1QVpmY1c5a1ZYOHJMeUlXL1BCbzJXQkg1em0yc3lkTStpeFVz"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: togglemaster
  labels:
    app: analytics-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: 007907262286.dkr.ecr.us-east-1.amazonaws.com/analytics-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          envFrom:
            - configMapRef:
                name: analytics-service-config
            - secretRef:
                name: analytics-service-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 15
            periodSeconds: 20
