apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: togglemaster
data:
  PORT: "8004"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  AWS_REGION: "us-east-1"
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: togglemaster
type: Opaque
data:
  REDIS_URL: "Q0hBTkdFTUU="
  SERVICE_API_KEY: "Q0hBTkdFTUU="
  AWS_SQS_URL: "Q0hBTkdFTUU="
  AWS_ACCESS_KEY_ID: "Q0hBTkdFTUU="
  AWS_SECRET_ACCESS_KEY: "Q0hBTkdFTUU="
  AWS_SESSION_TOKEN: "Q0hBTkdFTUU="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: togglemaster
  labels:
    app: evaluation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: 007907262286.dkr.ecr.us-east-1.amazonaws.com/evaluation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: evaluation-service-config
            - secretRef:
                name: evaluation-service-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 15
            periodSeconds: 20
